= Pivotal Cloud Foundry 101 Workshop

== COURSE OVERVIEW

This course provides students with the concepts and experience needed to work with and deploy applications on Pivotal Cloud Foundry. Students will gain experience in pushing apps to Cloud Foundry, accessing logs, and scaling. Students will explore topics directly related to the design and running of cloud native applications, including micro-service architectures, blue-green deployments, and continuous delivery.

== COURSE DURATION

Instructor-led: 1 day

== TARGET AUDIENCE

Application developers & architects seeking introductory understanding of Cloud Foundry and experience using it to deploy, manage, and scale applications.

== PREREQUISITES

Understanding of application development and deployment. This course is aimed at developers regardless of your development language of choice. No specific programming language is needed or assumed. The Boeing environment favors Java or .Net. The hands on Labs will primarily be based on languages that target the Java or .Net core runtime.

== COURSE OBJECTIVES

At the end of the training, participants should have an understanding of the following:

* Understand the differences between traditional IT provisioning, Infrastructure as a Service and Platform as a Service
* Explain organizations, spaces, routes, services (managed, user- defined), manifests, build packs, applications and droplets
* Identify Pivotal Cloud Foundry components: Router, Cloud Controller, Health Manager, Loggregator and Cells
* Deploy pre-existing applications to Pivotal Cloud Foundry, obtain logs, debug deployment issues, scale, start, stop, bind to services
* Use the command-line interface and Apps Manager to work with Pivotal Cloud Foundry
* Understand the impact of the cloud environment on application architecture
* Perform zero-downtime deployments
* Understand the role of services in Pivotal Cloud Foundry, gain experience using one or more examples
* Understand the purpose of build packs, gain experience specifying build packs and making configuration changes

== AGENDA / SCHEDULE

8:30 AM - 9:15 AM:: 
 * Session 1: _Cloud Native Introduction & Building Microservices_

Session 1 is an overview of Cloud Foundry and how you can support a multi-cloud portable strategy for applications and pipelines with minimal overhead.

9:15 AM - 9:30 AM:: BREAK

9:30 AM - 10:30 AM:: 
 * Session 2: _Cloud Foundry Architecture and Operations_

Session 2 is a deep dive on Platforms, Cloud Foundry, and Containers from both a dev and ops perspective

10:30 AM - 11:00 AM:: 
 * Laptop preparation

11:00 AM - 12:00 PM::
 * Developer Workshop (Part 1): _Pushing Code w/ PCF_

12:00 PM - 1:00 PM:: LUNCH

1:00 PM - 3:00 PM:: 
  * Developer Workshop (Part 2): _Continued hands-on w/ PCF_

3:00 PM - 3:30 PM:: Wrap Up, Q/A, Feedback

== Course Materials

* Session 1: link:presentations/Intro-Pivotal.pptx[Introduction]
* Session 2: link:presentations/PCF-Architecture.pptx[Cloud Foundry Architecture and Operations]

* Developer Workshop
** Pre-work
*** link:labs/README.adoc[Get Environment Access]
** Lab 1 - From Zero to Pushing Your First Application
*** link:labs/lab1/README.adoc[**Java** Application]
*** link:labs/lab1/cloud-native-spring.adoc[**Spring Boot** Application (start.spring.io)]
*** link:labs/lab1/lab-ruby.adoc[**Ruby** Application]
*** link:labs/lab1/lab-node.adoc[**NodeJS** Application]
*** link:labs/lab1/lab-dotnet.adoc[**.NET** Application]
** link:labs/lab2/README.adoc[Lab 2 - Binding to Cloud Foundry Services]
** link:labs/lab3/README.adoc[Lab 3 - Operating Your Application]
** link:labs/lab4/README.adoc[Lab 4 - Monitoring Your Application]
** Advanced Lab - Jenkins Integration
*** link:labs/lab5/README.adoc[Java App - Gradle Build]
** For further exploration check-out these projects 
*** https://github.com/pacphi/track-shipments[Spring Boot Track Shipments example]
*** https://github.com/pacphi/spring-boot-mongodb-example[Spring Boot MongoDB example]
*** https://github.com/pacphi/spring-boot-cassandra-customer-starter[Spring Boot Cassandra example]
*** https://spring.io/guides/gs/centralized-configuration/[Centralized configuration with Spring Cloud Config Server]